# Group information
name = "neo-full"                            # name of the group (not case sensitive)
alias = "neo-all"                            # alias of the group (optional)
packages = ["neo", "dash"]                   # list of packages in the group
supported_os = ["macOS", "Linux", "Windows"] # list of supported OS