[neo]

# Neo general information
[neo.general]
name = 'neo'                                         # name of neo (not case sensitive)
author = 'miten'                                     # author of neo
version = '0.1.0'                                    # version of neo
description = 'neo - cross platform package manager' # description of neo (optional)
license = 'zlib'                                     # license of neo 
repository = 'https://github.com/m1ten/neo'          # repository of neo 


# Neo package information
[neo.package]
mirrors = ['']   # Mirror list in preferred order (optional)
installed = [''] # Installed packages 

[neo.directory]
dir_nix = '~/neo'                  # Directory of neo on nix
dir_win = 'C:\\neo'                # Directory of neo on windows
install_dir_nix = '{dir_nix}/bin'  # Installation directory for nix
install_dir_win = '{dir_win}\\bin' # Installation directory for windows
cache_dir_nix = '{dir_nix}/cache'  # Cache directory for nix
cache_dir_win = '{dir_win}\\cache' # Cache directory for windows
temp_dir_nix = '{dir_nix}/temp'    # Temporary directory for nix
temp_dir_win = '{dir_win}\\temp'   # Temporary directory for windows
