[package]
name = "wix"
version = "0.1.0"
authors = ["miten"]
edition = "2021"
description = "wix - cross platform package manager"
readme = "README.md"
repository = "https://github.com/m1ten/wix"
license = "zlib"

[lib]
name = "wix"
path = "src/lib.rs"

[dependencies]
clap = "2.33.3"
pyo3 = { version = "0.15.0", features = ["auto-initialize"] }
reqwest = { version = "0.11.6", features = ["blocking"] }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"