[package]
name = "dash"
version = "0.1.0"
authors = ["miten"]
edition = "2021"
description = "dash your way through OS post-install"
readme = "README.md"
repository = "https://github.com/m1ten/dash"
license = "zlib"

[dependencies]
clap = "2.33.3"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
ron = "0.6.5"
serde_yaml = "0.8.21"
dashpy = { git = "https://github.com/m1ten/dash-priv/", branch = "python" }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"