[package]
name = "neopkg"
version = "0.0.1"
authors = ["miten <git.pub@icloud.com>"]
edition = "2021"
description = "cross platform package manager"
readme = "README.md"
repository = "https://github.com/m1ten/neopkg"
license = "Apache-2.0"
publish = false

[lib]
name = "neopkg"
path = "src/lib/mod.rs"

[dependencies]
clap = "3.1.2"
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
indexmap = "1.8.0"
which = "4.2.4"
dirs = "4.0.0"
tokio = { version = "1.17.0", features = ["full"] }
online = "3.0.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
bat = "0.20.0"
smart-default = "0.6.0"
regex = "1.5.4"
futures = "0.3.21"

[target.'cfg(unix)'.dependencies]
nix = "0.23.1"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true