[package]
name = "krait"
version = "0.0.1"
authors = ["miten <57693631+m1ten@users.noreply.github.com>"]
edition = "2021"
description = "cross platform package manager"
readme = "README.md"
repository = "https://github.com/m1ten/krait"
license = "Apache-2.0"
publish = false

[lib]
name = "krait"
path = "src/lib/mod.rs"

[dependencies]
clap = "3.1.18"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
indexmap = "1.8.2"
which = "4.2.5"
dirs = "4.0.0"
tokio = { version = "1.18.2", features = ["full"] }
online = "3.0.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
bat = "0.21.0"
smart-default = "0.6.0"
regex = "1.5.6"
futures = "0.3.21"

[target.'cfg(unix)'.dependencies]
nix = "0.24.1"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true