[package]
name = "wix_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "wix_py"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.14.5", features = ["extension-module"] }
reqwest = { version = "0.11.6", features = ["blocking"] }

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
panic = "abort"