[package]
name = "wix"
version = "0.1.0"
authors = ["miten"]
edition = "2021"
description = "cross platform package manager"
readme = "README.md"
repository = "https://github.com/m1ten/wix"
license = "Zlib"

[lib]
name = "wix"
path = "src/lib/mod.rs"

[dependencies] 
clap = "2.34.0"
pyo3 = { version = "0.15.1", features = ["auto-initialize"] }
reqwest = { version = "0.11.9", features = ["blocking"] }
indexmap = "1.8.0"
which = "4.2.2"
dirs = "4.0.0"
tokio = { version = "1.15.0", features = ["full"] }
online = "3.0.1"

[target.'cfg(unix)'.dependencies]
nix = "0.23.0"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1.2"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"