[package]
name = "neopkg"
version = "0.1.0"
authors = ["miten"]
edition = "2021"
description = "cross platform package manager"
readme = "README.md"
repository = "https://github.com/m1ten/neopkg"
license = "Apache-2.0"

[lib]
name = "neopkg"
path = "src/lib/mod.rs"

[dependencies]
clap = "3.1.0"
reqwest = { version = "0.11.9", features = ["blocking"] }
indexmap = "1.8.0"
which = "4.2.4"
dirs = "4.0.0"
tokio = { version = "1.17.0", features = ["full"] }
online = "3.0.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
bat = "0.19.0"
smart-default = "0.6.0"

[target.'cfg(unix)'.dependencies]
nix = "0.23.1"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1.2"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = true