cargo-features = ["strip"]

[package]
name = "dash"
version = "0.1.0"
authors = ["miten"]
edition = "2021"
description = "dash your way through OS post-install"
readme = "README.md"
repository = "https://github.com/m1ten/dash"
license = "zlib"

[dependencies]
clap = "2.33.3"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"