[info]
author = 'miten'
description = 'dash your way through OS post-install'
name = 'dash'
version = '0.1.0'

[setup]
os = 'Windows'
pkg_mgr = 'winget'

[[setup.dotfile]]
name = '.vimrc'
new_path = '~/.vimrc'
prv_path = '~/Downloads/.vimrc'
symlink = false

[[setup.dotfile]]
name = '.zshrc'
new_path = '~/.zshrc'
prv_path = '~/Downloads/.zshrc'
symlink = true

[[setup.pkg]]
name = 'Chrome'
prv_path = '~/Downloads/Chrome'
