name: compile and release neo stable

on:
  push:
    tags: 
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:

  create-release:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'

  build-windows:
    
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        override: true

    - name: Build
      run: cargo build --release
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/neo.exe
        asset_name: neo-windows-x86_64.exe
        tag: ${{ github.ref }}
        overwrite: false
        prerelease: true
      
  build-linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'

    - name: Install mold
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -LO https://github.com/rui314/mold/releases/download/v1.1/mold-1.1-x86_64-linux.tar.gz
        tar -xvf mold-1.1-x86_64-linux.tar.gz
        sudo mv mold-1.1-x86_64-linux/mold /usr/local/bin/mold

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/neo
        asset_name: neo-linux-x86_64
        tag: ${{ github.ref }}
        overwrite: false
        prerelease: true
    
  build-macos:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'

    - name: Install mold
      run: |
        brew update
        brew install mold 

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-apple-darwin
        default: true
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/neo
        asset_name: neo-macos-x86_64
        tag: ${{ github.ref }}
        overwrite: false
        prerelease: true