name: compile and release neopkg stable

on:
  push:
    tags: 
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:

  create-release:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'

  build-windows:
    
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        override: true

    - name: Build
      run: cargo build --release
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/neopkg.exe
        asset_name: neopkg-windows-x86_64.exe
        tag: ${{ github.ref }}
        overwrite: false
        prerelease: true
      
  build-linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/neopkg
        asset_name: neopkg-linux-x86_64
        tag: ${{ github.ref }}
        overwrite: false
        prerelease: true
    
  build-macos:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-apple-darwin
        default: true
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/neopkg
        asset_name: neopkg-macos-x86_64
        tag: ${{ github.ref }}
        overwrite: false
        prerelease: true